---
controller:
  image:
    repository: {{ nginx_image.split(":")[0] }}
    tag: "{{ nginx_image.split(":")[1] }}"
  service:
    type: LoadBalancer
    loadBalancerIP: {{ ingress_static_ip }}
    externalIPs: # used to access Unifi UI prior to MetalLB setup
      - {{ansible_default_ipv4.address}}
    annotations:
      metallb.universe.tf/allow-shared-ip: ingress-shared
      port-forwarding.lylefranklin.com/enable: "true"
  extraArgs:
    default-ssl-certificate: kube-system/default-backend-cert-secret
defaultBackend:
  image:
    repository: {{ nginx_backend_image.split(":")[0] }}
    tag: "{{ nginx_backend_image.split(":")[1] }}"
