---
- name: template port-forwarding config
  template:
    src: ./port-forwarding-values.yml
    dest: /tmp/
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

- name: install port-forwarding
  shell: >
    helm upgrade
    --install
    --values /tmp/port-forwarding-values.yml
    port-forwarding
    {{ port_forwarding.chart }}
